// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mars/civilization/v1/query.proto

package v1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryGoalRequest identifies one goal.
type QueryGoalRequest struct {
	GoalId string `protobuf:"bytes,1,opt,name=goal_id,json=goalId,proto3" json:"goal_id,omitempty"`
}

func (m *QueryGoalRequest) Reset()         { *m = QueryGoalRequest{} }
func (m *QueryGoalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGoalRequest) ProtoMessage()    {}
func (*QueryGoalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{0}
}
func (m *QueryGoalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGoalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGoalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGoalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGoalRequest.Merge(m, src)
}
func (m *QueryGoalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGoalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGoalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGoalRequest proto.InternalMessageInfo

func (m *QueryGoalRequest) GetGoalId() string {
	if m != nil {
		return m.GoalId
	}
	return ""
}

// QueryGoalResponse returns one goal.
type QueryGoalResponse struct {
	Goal *Goal `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
}

func (m *QueryGoalResponse) Reset()         { *m = QueryGoalResponse{} }
func (m *QueryGoalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGoalResponse) ProtoMessage()    {}
func (*QueryGoalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{1}
}
func (m *QueryGoalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGoalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGoalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGoalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGoalResponse.Merge(m, src)
}
func (m *QueryGoalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGoalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGoalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGoalResponse proto.InternalMessageInfo

func (m *QueryGoalResponse) GetGoal() *Goal {
	if m != nil {
		return m.Goal
	}
	return nil
}

// QueryProposalRequest identifies the current proposal version.
type QueryProposalRequest struct {
	ProposalId string `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
}

func (m *QueryProposalRequest) Reset()         { *m = QueryProposalRequest{} }
func (m *QueryProposalRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProposalRequest) ProtoMessage()    {}
func (*QueryProposalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{2}
}
func (m *QueryProposalRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProposalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProposalRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProposalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProposalRequest.Merge(m, src)
}
func (m *QueryProposalRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProposalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProposalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProposalRequest proto.InternalMessageInfo

func (m *QueryProposalRequest) GetProposalId() string {
	if m != nil {
		return m.ProposalId
	}
	return ""
}

// QueryProposalResponse returns the current proposal version.
type QueryProposalResponse struct {
	Proposal *Proposal `protobuf:"bytes,1,opt,name=proposal,proto3" json:"proposal,omitempty"`
}

func (m *QueryProposalResponse) Reset()         { *m = QueryProposalResponse{} }
func (m *QueryProposalResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProposalResponse) ProtoMessage()    {}
func (*QueryProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{3}
}
func (m *QueryProposalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProposalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProposalResponse.Merge(m, src)
}
func (m *QueryProposalResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProposalResponse proto.InternalMessageInfo

func (m *QueryProposalResponse) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

// QueryVoteRequestRequest identifies one eligible Praxeon's request.
type QueryVoteRequestRequest struct {
	ProposalId string `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	PraxeonId  string `protobuf:"bytes,2,opt,name=praxeon_id,json=praxeonId,proto3" json:"praxeon_id,omitempty"`
}

func (m *QueryVoteRequestRequest) Reset()         { *m = QueryVoteRequestRequest{} }
func (m *QueryVoteRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryVoteRequestRequest) ProtoMessage()    {}
func (*QueryVoteRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{4}
}
func (m *QueryVoteRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVoteRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVoteRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVoteRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVoteRequestRequest.Merge(m, src)
}
func (m *QueryVoteRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryVoteRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVoteRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVoteRequestRequest proto.InternalMessageInfo

func (m *QueryVoteRequestRequest) GetProposalId() string {
	if m != nil {
		return m.ProposalId
	}
	return ""
}

func (m *QueryVoteRequestRequest) GetPraxeonId() string {
	if m != nil {
		return m.PraxeonId
	}
	return ""
}

// QueryVoteRequestResponse returns one vote request.
type QueryVoteRequestResponse struct {
	VoteRequest *VoteRequest `protobuf:"bytes,1,opt,name=vote_request,json=voteRequest,proto3" json:"vote_request,omitempty"`
}

func (m *QueryVoteRequestResponse) Reset()         { *m = QueryVoteRequestResponse{} }
func (m *QueryVoteRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryVoteRequestResponse) ProtoMessage()    {}
func (*QueryVoteRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{5}
}
func (m *QueryVoteRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryVoteRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryVoteRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryVoteRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryVoteRequestResponse.Merge(m, src)
}
func (m *QueryVoteRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryVoteRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryVoteRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryVoteRequestResponse proto.InternalMessageInfo

func (m *QueryVoteRequestResponse) GetVoteRequest() *VoteRequest {
	if m != nil {
		return m.VoteRequest
	}
	return nil
}

// QueryDecisionRequest identifies the finalized proposal.
type QueryDecisionRequest struct {
	ProposalId string `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
}

func (m *QueryDecisionRequest) Reset()         { *m = QueryDecisionRequest{} }
func (m *QueryDecisionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDecisionRequest) ProtoMessage()    {}
func (*QueryDecisionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{6}
}
func (m *QueryDecisionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDecisionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDecisionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDecisionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDecisionRequest.Merge(m, src)
}
func (m *QueryDecisionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDecisionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDecisionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDecisionRequest proto.InternalMessageInfo

func (m *QueryDecisionRequest) GetProposalId() string {
	if m != nil {
		return m.ProposalId
	}
	return ""
}

// QueryDecisionResponse returns one decision.
type QueryDecisionResponse struct {
	Decision *Decision `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
}

func (m *QueryDecisionResponse) Reset()         { *m = QueryDecisionResponse{} }
func (m *QueryDecisionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDecisionResponse) ProtoMessage()    {}
func (*QueryDecisionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{7}
}
func (m *QueryDecisionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDecisionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDecisionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDecisionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDecisionResponse.Merge(m, src)
}
func (m *QueryDecisionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDecisionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDecisionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDecisionResponse proto.InternalMessageInfo

func (m *QueryDecisionResponse) GetDecision() *Decision {
	if m != nil {
		return m.Decision
	}
	return nil
}

// QueryAgentSnapshotRequest identifies one Agent.
type QueryAgentSnapshotRequest struct {
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
}

func (m *QueryAgentSnapshotRequest) Reset()         { *m = QueryAgentSnapshotRequest{} }
func (m *QueryAgentSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAgentSnapshotRequest) ProtoMessage()    {}
func (*QueryAgentSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{8}
}
func (m *QueryAgentSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAgentSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAgentSnapshotRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAgentSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentSnapshotRequest.Merge(m, src)
}
func (m *QueryAgentSnapshotRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAgentSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentSnapshotRequest proto.InternalMessageInfo

func (m *QueryAgentSnapshotRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

// QueryAgentSnapshotResponse returns one machine-readable Agent snapshot.
type QueryAgentSnapshotResponse struct {
	Snapshot *AgentSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
}

func (m *QueryAgentSnapshotResponse) Reset()         { *m = QueryAgentSnapshotResponse{} }
func (m *QueryAgentSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAgentSnapshotResponse) ProtoMessage()    {}
func (*QueryAgentSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{9}
}
func (m *QueryAgentSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAgentSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAgentSnapshotResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAgentSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentSnapshotResponse.Merge(m, src)
}
func (m *QueryAgentSnapshotResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAgentSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentSnapshotResponse proto.InternalMessageInfo

func (m *QueryAgentSnapshotResponse) GetSnapshot() *AgentSnapshot {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

// QueryEventsRequest requests events strictly after after_cursor.
type QueryEventsRequest struct {
	AgentId     string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AfterCursor uint64 `protobuf:"varint,2,opt,name=after_cursor,json=afterCursor,proto3" json:"after_cursor,omitempty"`
	Limit       uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *QueryEventsRequest) Reset()         { *m = QueryEventsRequest{} }
func (m *QueryEventsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEventsRequest) ProtoMessage()    {}
func (*QueryEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{10}
}
func (m *QueryEventsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEventsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEventsRequest.Merge(m, src)
}
func (m *QueryEventsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEventsRequest proto.InternalMessageInfo

func (m *QueryEventsRequest) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *QueryEventsRequest) GetAfterCursor() uint64 {
	if m != nil {
		return m.AfterCursor
	}
	return 0
}

func (m *QueryEventsRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

// QueryEventsResponse returns visible events and the latest delivered cursor.
type QueryEventsResponse struct {
	Events     []*EventEnvelope `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextCursor uint64           `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
}

func (m *QueryEventsResponse) Reset()         { *m = QueryEventsResponse{} }
func (m *QueryEventsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEventsResponse) ProtoMessage()    {}
func (*QueryEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d7aaa8c4e5da0c0, []int{11}
}
func (m *QueryEventsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEventsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEventsResponse.Merge(m, src)
}
func (m *QueryEventsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEventsResponse proto.InternalMessageInfo

func (m *QueryEventsResponse) GetEvents() []*EventEnvelope {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *QueryEventsResponse) GetNextCursor() uint64 {
	if m != nil {
		return m.NextCursor
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryGoalRequest)(nil), "mars.civilization.v1.QueryGoalRequest")
	proto.RegisterType((*QueryGoalResponse)(nil), "mars.civilization.v1.QueryGoalResponse")
	proto.RegisterType((*QueryProposalRequest)(nil), "mars.civilization.v1.QueryProposalRequest")
	proto.RegisterType((*QueryProposalResponse)(nil), "mars.civilization.v1.QueryProposalResponse")
	proto.RegisterType((*QueryVoteRequestRequest)(nil), "mars.civilization.v1.QueryVoteRequestRequest")
	proto.RegisterType((*QueryVoteRequestResponse)(nil), "mars.civilization.v1.QueryVoteRequestResponse")
	proto.RegisterType((*QueryDecisionRequest)(nil), "mars.civilization.v1.QueryDecisionRequest")
	proto.RegisterType((*QueryDecisionResponse)(nil), "mars.civilization.v1.QueryDecisionResponse")
	proto.RegisterType((*QueryAgentSnapshotRequest)(nil), "mars.civilization.v1.QueryAgentSnapshotRequest")
	proto.RegisterType((*QueryAgentSnapshotResponse)(nil), "mars.civilization.v1.QueryAgentSnapshotResponse")
	proto.RegisterType((*QueryEventsRequest)(nil), "mars.civilization.v1.QueryEventsRequest")
	proto.RegisterType((*QueryEventsResponse)(nil), "mars.civilization.v1.QueryEventsResponse")
}

func init() { proto.RegisterFile("mars/civilization/v1/query.proto", fileDescriptor_3d7aaa8c4e5da0c0) }

var fileDescriptor_3d7aaa8c4e5da0c0 = []byte{
	// 722 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xcf, 0x4f, 0xd4, 0x40,
	0x14, 0xc7, 0x19, 0x7e, 0x2c, 0xcb, 0x5b, 0x48, 0x74, 0xc4, 0xb0, 0x34, 0xba, 0x2e, 0x35, 0x0a,
	0x4a, 0xe8, 0x00, 0x2a, 0x12, 0x4d, 0x34, 0x0a, 0xc4, 0x6c, 0xbc, 0xe8, 0x92, 0x98, 0x68, 0x62,
	0xb0, 0xd2, 0x71, 0x69, 0x52, 0x3a, 0xa5, 0x53, 0x1a, 0x94, 0xec, 0xc5, 0x83, 0x67, 0x13, 0xe3,
	0xc5, 0xab, 0x57, 0xff, 0x01, 0xff, 0x03, 0x8f, 0x24, 0x26, 0xc6, 0xa3, 0x01, 0xff, 0x10, 0xd3,
	0xd7, 0x69, 0xf7, 0x07, 0xb5, 0x2c, 0xc7, 0x79, 0xf3, 0x7d, 0xef, 0x7d, 0xfa, 0xba, 0xef, 0xbb,
	0x85, 0xea, 0xb6, 0xe9, 0x4b, 0xb6, 0x69, 0x87, 0xb6, 0x63, 0xbf, 0x33, 0x03, 0x5b, 0xb8, 0x2c,
	0x5c, 0x60, 0x3b, 0xbb, 0xdc, 0x7f, 0x6b, 0x78, 0xbe, 0x08, 0x04, 0x1d, 0x8f, 0x14, 0x46, 0xbb,
	0xc2, 0x08, 0x17, 0xb4, 0x0b, 0x0d, 0x21, 0x1a, 0x0e, 0x67, 0xa6, 0x67, 0x33, 0xd3, 0x75, 0x45,
	0x80, 0x37, 0x32, 0xce, 0xd1, 0xb2, 0xab, 0x6e, 0x0b, 0x8b, 0x3b, 0xb1, 0x42, 0x9f, 0x85, 0x33,
	0x4f, 0xa3, 0x26, 0x8f, 0x84, 0xe9, 0xd4, 0xf9, 0xce, 0x2e, 0x97, 0x01, 0x9d, 0x80, 0xe1, 0x86,
	0x30, 0x9d, 0x0d, 0xdb, 0x2a, 0x93, 0x2a, 0x99, 0x19, 0xa9, 0x17, 0xa2, 0x63, 0xcd, 0xd2, 0x57,
	0xe0, 0x6c, 0x9b, 0x58, 0x7a, 0xc2, 0x95, 0x9c, 0x1a, 0x30, 0x18, 0x5d, 0xa3, 0xb4, 0xb4, 0xa8,
	0x19, 0x59, 0x98, 0x06, 0x66, 0xa0, 0x4e, 0xbf, 0x0d, 0xe3, 0x58, 0xe4, 0x89, 0x2f, 0x3c, 0x21,
	0x5b, 0x5d, 0x2f, 0x41, 0xc9, 0x53, 0xa1, 0x56, 0x67, 0x48, 0x42, 0x35, 0x4b, 0x5f, 0x87, 0xf3,
	0x5d, 0x89, 0x8a, 0xe0, 0x0e, 0x14, 0x13, 0x99, 0xa2, 0xa8, 0x64, 0x53, 0xa4, 0x99, 0xa9, 0x5e,
	0x7f, 0x0e, 0x13, 0x58, 0xf4, 0x99, 0x08, 0xb8, 0x22, 0xe9, 0x15, 0x88, 0x5e, 0x04, 0xf0, 0x7c,
	0x73, 0x8f, 0x0b, 0x37, 0xba, 0xef, 0xc7, 0xfb, 0x11, 0x15, 0xa9, 0x59, 0xfa, 0x2b, 0x28, 0x1f,
	0x2f, 0xad, 0x90, 0x57, 0x61, 0x34, 0x14, 0x01, 0xdf, 0xf0, 0xe3, 0xb8, 0xc2, 0x9e, 0xca, 0xc6,
	0x6e, 0x2f, 0x50, 0x0a, 0x5b, 0x87, 0x74, 0x94, 0xab, 0x7c, 0xd3, 0x96, 0xb6, 0x70, 0x4f, 0x3d,
	0xca, 0x56, 0x62, 0x6b, 0x94, 0x96, 0x8a, 0xe5, 0x8f, 0x32, 0xcd, 0x4c, 0xf5, 0xfa, 0x12, 0x4c,
	0x62, 0xd1, 0x07, 0x0d, 0xee, 0x06, 0xeb, 0xae, 0xe9, 0xc9, 0x2d, 0x91, 0x0e, 0x73, 0x12, 0x8a,
	0x66, 0x14, 0x6f, 0xf1, 0x0c, 0xe3, 0xb9, 0x66, 0xe9, 0x2f, 0x41, 0xcb, 0xca, 0x53, 0x44, 0xf7,
	0xa1, 0x28, 0x55, 0x4c, 0x11, 0x5d, 0xce, 0x26, 0xea, 0x4c, 0x4f, 0x93, 0xf4, 0x2d, 0xa0, 0x58,
	0x7e, 0x2d, 0xe4, 0x6e, 0x20, 0x4f, 0xe6, 0xa1, 0x53, 0x30, 0x6a, 0xbe, 0x09, 0xb8, 0xbf, 0xb1,
	0xb9, 0xeb, 0x4b, 0xe1, 0xe3, 0x8b, 0x1d, 0xac, 0x97, 0x30, 0xb6, 0x82, 0x21, 0x3a, 0x0e, 0x43,
	0x8e, 0xbd, 0x6d, 0x07, 0xe5, 0x81, 0x2a, 0x99, 0x19, 0xab, 0xc7, 0x07, 0x5d, 0xc2, 0xb9, 0x8e,
	0x4e, 0xea, 0x09, 0xee, 0x42, 0x81, 0x63, 0xa4, 0x4c, 0xaa, 0x03, 0xff, 0xe7, 0xc7, 0xac, 0x35,
	0x37, 0xe4, 0x8e, 0xf0, 0x78, 0x5d, 0xa5, 0x44, 0xaf, 0xd2, 0xe5, 0x7b, 0x41, 0x27, 0x0b, 0x44,
	0xa1, 0x18, 0x65, 0xf1, 0xd7, 0x30, 0x0c, 0x61, 0x57, 0xfa, 0x81, 0xc0, 0x60, 0xb4, 0x67, 0xf4,
	0x6a, 0x76, 0x83, 0xee, 0x3d, 0xd7, 0xa6, 0x4f, 0xd4, 0xc5, 0x4f, 0xa0, 0xcf, 0xbd, 0xff, 0xf9,
	0xf7, 0x53, 0xff, 0x34, 0xbd, 0xc2, 0x32, 0xfd, 0x24, 0x5a, 0x6b, 0xc9, 0xf6, 0x95, 0x67, 0x34,
	0xe9, 0x17, 0x02, 0xc5, 0x64, 0xd5, 0xe8, 0xf5, 0x9c, 0x26, 0x5d, 0x16, 0xa0, 0xcd, 0xf6, 0xa4,
	0x55, 0x50, 0xb7, 0x10, 0x8a, 0xd1, 0xb9, 0x6c, 0xa8, 0xe4, 0xd7, 0x2e, 0xd9, 0x7e, 0xdb, 0x2e,
	0x34, 0xe9, 0x77, 0x02, 0xa5, 0xb6, 0x85, 0xa2, 0x73, 0x39, 0x3d, 0x8f, 0x9b, 0x82, 0x66, 0xf4,
	0x2a, 0x57, 0x94, 0x8f, 0x91, 0x72, 0x8d, 0xae, 0x9c, 0x8a, 0x92, 0x29, 0x5f, 0xc0, 0x70, 0xe2,
	0x30, 0x4d, 0xfa, 0x95, 0x40, 0x31, 0x59, 0xbc, 0xdc, 0xc1, 0x76, 0x19, 0x42, 0xee, 0x60, 0xbb,
	0x3d, 0x40, 0xbf, 0x87, 0xc8, 0xcb, 0x74, 0xe9, 0x74, 0xc8, 0x89, 0x0f, 0xd0, 0x6f, 0x04, 0xc6,
	0x3a, 0x96, 0x91, 0xb2, 0x9c, 0xf6, 0x59, 0x6e, 0xa1, 0xcd, 0xf7, 0x9e, 0xa0, 0xa0, 0x97, 0x11,
	0x7a, 0x91, 0xce, 0x67, 0x43, 0xe3, 0x6e, 0x4b, 0xb6, 0x9f, 0xec, 0x7c, 0x93, 0x25, 0xfe, 0x40,
	0x3f, 0x13, 0x28, 0xc4, 0x1b, 0x4b, 0x67, 0x72, 0xda, 0x76, 0xd8, 0x87, 0x76, 0xad, 0x07, 0xa5,
	0x22, 0x5b, 0x42, 0xb2, 0x79, 0x6a, 0xf4, 0x4a, 0x16, 0x6f, 0xfe, 0xc3, 0x9b, 0x3f, 0x0e, 0x2b,
	0xe4, 0xe0, 0xb0, 0x42, 0xfe, 0x1c, 0x56, 0xc8, 0xc7, 0xa3, 0x4a, 0xdf, 0xc1, 0x51, 0xa5, 0xef,
	0xf7, 0x51, 0xa5, 0xef, 0x85, 0x86, 0x85, 0xf6, 0x3a, 0x4b, 0x45, 0x1f, 0x00, 0xe1, 0xc2, 0xeb,
	0x02, 0xfe, 0xad, 0xdf, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0x70, 0x65, 0x88, 0xdb, 0x50, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Goal returns one Goal.
	Goal(ctx context.Context, in *QueryGoalRequest, opts ...grpc.CallOption) (*QueryGoalResponse, error)
	// Proposal returns the current proposal version.
	Proposal(ctx context.Context, in *QueryProposalRequest, opts ...grpc.CallOption) (*QueryProposalResponse, error)
	// VoteRequest returns the delivery package for one eligible Praxeon ID.
	VoteRequest(ctx context.Context, in *QueryVoteRequestRequest, opts ...grpc.CallOption) (*QueryVoteRequestResponse, error)
	// Decision returns the finalized result of one Proposal.
	Decision(ctx context.Context, in *QueryDecisionRequest, opts ...grpc.CallOption) (*QueryDecisionResponse, error)
	// AgentSnapshot returns one Agent's machine-readable current view.
	AgentSnapshot(ctx context.Context, in *QueryAgentSnapshotRequest, opts ...grpc.CallOption) (*QueryAgentSnapshotResponse, error)
	// Events returns visible events after one cursor for idempotent Agent consumption.
	Events(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Goal(ctx context.Context, in *QueryGoalRequest, opts ...grpc.CallOption) (*QueryGoalResponse, error) {
	out := new(QueryGoalResponse)
	err := c.cc.Invoke(ctx, "/mars.civilization.v1.Query/Goal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Proposal(ctx context.Context, in *QueryProposalRequest, opts ...grpc.CallOption) (*QueryProposalResponse, error) {
	out := new(QueryProposalResponse)
	err := c.cc.Invoke(ctx, "/mars.civilization.v1.Query/Proposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) VoteRequest(ctx context.Context, in *QueryVoteRequestRequest, opts ...grpc.CallOption) (*QueryVoteRequestResponse, error) {
	out := new(QueryVoteRequestResponse)
	err := c.cc.Invoke(ctx, "/mars.civilization.v1.Query/VoteRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Decision(ctx context.Context, in *QueryDecisionRequest, opts ...grpc.CallOption) (*QueryDecisionResponse, error) {
	out := new(QueryDecisionResponse)
	err := c.cc.Invoke(ctx, "/mars.civilization.v1.Query/Decision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AgentSnapshot(ctx context.Context, in *QueryAgentSnapshotRequest, opts ...grpc.CallOption) (*QueryAgentSnapshotResponse, error) {
	out := new(QueryAgentSnapshotResponse)
	err := c.cc.Invoke(ctx, "/mars.civilization.v1.Query/AgentSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Events(ctx context.Context, in *QueryEventsRequest, opts ...grpc.CallOption) (*QueryEventsResponse, error) {
	out := new(QueryEventsResponse)
	err := c.cc.Invoke(ctx, "/mars.civilization.v1.Query/Events", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Goal returns one Goal.
	Goal(context.Context, *QueryGoalRequest) (*QueryGoalResponse, error)
	// Proposal returns the current proposal version.
	Proposal(context.Context, *QueryProposalRequest) (*QueryProposalResponse, error)
	// VoteRequest returns the delivery package for one eligible Praxeon ID.
	VoteRequest(context.Context, *QueryVoteRequestRequest) (*QueryVoteRequestResponse, error)
	// Decision returns the finalized result of one Proposal.
	Decision(context.Context, *QueryDecisionRequest) (*QueryDecisionResponse, error)
	// AgentSnapshot returns one Agent's machine-readable current view.
	AgentSnapshot(context.Context, *QueryAgentSnapshotRequest) (*QueryAgentSnapshotResponse, error)
	// Events returns visible events after one cursor for idempotent Agent consumption.
	Events(context.Context, *QueryEventsRequest) (*QueryEventsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Goal(ctx context.Context, req *QueryGoalRequest) (*QueryGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Goal not implemented")
}
func (*UnimplementedQueryServer) Proposal(ctx context.Context, req *QueryProposalRequest) (*QueryProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proposal not implemented")
}
func (*UnimplementedQueryServer) VoteRequest(ctx context.Context, req *QueryVoteRequestRequest) (*QueryVoteRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VoteRequest not implemented")
}
func (*UnimplementedQueryServer) Decision(ctx context.Context, req *QueryDecisionRequest) (*QueryDecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decision not implemented")
}
func (*UnimplementedQueryServer) AgentSnapshot(ctx context.Context, req *QueryAgentSnapshotRequest) (*QueryAgentSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentSnapshot not implemented")
}
func (*UnimplementedQueryServer) Events(ctx context.Context, req *QueryEventsRequest) (*QueryEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Events not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Goal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Goal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mars.civilization.v1.Query/Goal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Goal(ctx, req.(*QueryGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Proposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Proposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mars.civilization.v1.Query/Proposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Proposal(ctx, req.(*QueryProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_VoteRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVoteRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).VoteRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mars.civilization.v1.Query/VoteRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).VoteRequest(ctx, req.(*QueryVoteRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Decision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Decision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mars.civilization.v1.Query/Decision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Decision(ctx, req.(*QueryDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AgentSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAgentSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AgentSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mars.civilization.v1.Query/AgentSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AgentSnapshot(ctx, req.(*QueryAgentSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Events_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Events(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mars.civilization.v1.Query/Events",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Events(ctx, req.(*QueryEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mars.civilization.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Goal",
			Handler:    _Query_Goal_Handler,
		},
		{
			MethodName: "Proposal",
			Handler:    _Query_Proposal_Handler,
		},
		{
			MethodName: "VoteRequest",
			Handler:    _Query_VoteRequest_Handler,
		},
		{
			MethodName: "Decision",
			Handler:    _Query_Decision_Handler,
		},
		{
			MethodName: "AgentSnapshot",
			Handler:    _Query_AgentSnapshot_Handler,
		},
		{
			MethodName: "Events",
			Handler:    _Query_Events_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mars/civilization/v1/query.proto",
}

func (m *QueryGoalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGoalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGoalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GoalId) > 0 {
		i -= len(m.GoalId)
		copy(dAtA[i:], m.GoalId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.GoalId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGoalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGoalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGoalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Goal != nil {
		{
			size, err := m.Goal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProposalRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProposalRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProposalRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProposalId) > 0 {
		i -= len(m.ProposalId)
		copy(dAtA[i:], m.ProposalId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ProposalId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProposalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Proposal != nil {
		{
			size, err := m.Proposal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVoteRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVoteRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVoteRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PraxeonId) > 0 {
		i -= len(m.PraxeonId)
		copy(dAtA[i:], m.PraxeonId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PraxeonId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ProposalId) > 0 {
		i -= len(m.ProposalId)
		copy(dAtA[i:], m.ProposalId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ProposalId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryVoteRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryVoteRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryVoteRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VoteRequest != nil {
		{
			size, err := m.VoteRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDecisionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDecisionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDecisionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProposalId) > 0 {
		i -= len(m.ProposalId)
		copy(dAtA[i:], m.ProposalId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ProposalId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDecisionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDecisionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDecisionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Decision != nil {
		{
			size, err := m.Decision.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAgentSnapshotRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAgentSnapshotRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAgentSnapshotRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAgentSnapshotResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAgentSnapshotResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAgentSnapshotResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Snapshot != nil {
		{
			size, err := m.Snapshot.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEventsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEventsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEventsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Limit != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x18
	}
	if m.AfterCursor != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AfterCursor))
		i--
		dAtA[i] = 0x10
	}
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEventsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEventsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEventsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextCursor != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.NextCursor))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Events) > 0 {
		for iNdEx := len(m.Events) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Events[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGoalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GoalId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGoalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Goal != nil {
		l = m.Goal.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryProposalRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProposalId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryProposalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Proposal != nil {
		l = m.Proposal.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVoteRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProposalId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.PraxeonId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryVoteRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.VoteRequest != nil {
		l = m.VoteRequest.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDecisionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProposalId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDecisionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Decision != nil {
		l = m.Decision.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAgentSnapshotRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAgentSnapshotResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Snapshot != nil {
		l = m.Snapshot.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEventsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AfterCursor != 0 {
		n += 1 + sovQuery(uint64(m.AfterCursor))
	}
	if m.Limit != 0 {
		n += 1 + sovQuery(uint64(m.Limit))
	}
	return n
}

func (m *QueryEventsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Events) > 0 {
		for _, e := range m.Events {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.NextCursor != 0 {
		n += 1 + sovQuery(uint64(m.NextCursor))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGoalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGoalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGoalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GoalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGoalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGoalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGoalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Goal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Goal == nil {
				m.Goal = &Goal{}
			}
			if err := m.Goal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProposalRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProposalRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProposalRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProposalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProposalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProposalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proposal == nil {
				m.Proposal = &Proposal{}
			}
			if err := m.Proposal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVoteRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVoteRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVoteRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PraxeonId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PraxeonId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryVoteRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryVoteRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryVoteRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VoteRequest == nil {
				m.VoteRequest = &VoteRequest{}
			}
			if err := m.VoteRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDecisionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDecisionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDecisionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDecisionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDecisionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDecisionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decision", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Decision == nil {
				m.Decision = &Decision{}
			}
			if err := m.Decision.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAgentSnapshotRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAgentSnapshotRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAgentSnapshotRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAgentSnapshotResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAgentSnapshotResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAgentSnapshotResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Snapshot", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Snapshot == nil {
				m.Snapshot = &AgentSnapshot{}
			}
			if err := m.Snapshot.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEventsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEventsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEventsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AfterCursor", wireType)
			}
			m.AfterCursor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AfterCursor |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEventsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEventsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEventsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Events", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Events = append(m.Events, &EventEnvelope{})
			if err := m.Events[len(m.Events)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextCursor", wireType)
			}
			m.NextCursor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextCursor |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
